### ISSUE TITLE
Possibility to add model class properties in to_json()?

### ISSUE THREAD

**Issue by LaundroMat** [hiroaki-yamamoto/mongoengine-goodjson#135]
**Is your feature request related to a problem? Please describe.**
I have a model that contains a few calculated properties (e.g. time_since_last_update).

**Describe the solution you'd like**
Is there a way to get these model class properties returned by `.to_json()`?

**Comment by hiroaki-yamamoto** [comment]
How about using [this]?

[this]: https://github.com/hiroaki-yamamoto/omm

**Comment by LaundroMat** [comment]
Looks promising indeed, I'll give it a try!
