### ISSUE TITLE
Is FollowReferenceField implemented?

### ISSUE THREAD

**Issue by macfire** [hiroaki-yamamoto/mongoengine-goodjson#15]
It is unclear to me how to use FollowReferenceField.
The generated JSON only has the ObjectId, and not the referenced document.
Does this replace using the kwarg `follow_reference=True` ?

My models are setup as per example:

``` python
class Book(gj.Document):
  name = db.StringField(required=True)
  isbn = db.StringField(required=True)
  author = db.StringField(required=True)

class User(gj.Document):
  firstname = db.StringField(required=True)
  lastname = db.StringField(required=True)
  books_bought = db.ListField(gj.FollowReferenceField(Book))
  favorite_one = gj.FollowReferenceField(Book)
```

The generated output only has the ObjectId:

``` javascript
{
  "id": "570ee9d1fec55e755db82129",
  "firstname": "James",
  "lastname": "Smith",
  "books_bought": [
    "570eea0afec55e755db8212a",
    "570eea0bfec55e755db8212b",
    "570eea0bfec55e755db8212c"
  ],
  "favorite_one": "570eea0bfec55e755db8212b"
}
```

I've also tried using the kwarg  `follow_reference=True`, but receive an error:

``` console
...
web_1  |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
web_1  |     resp = meth(*args, **kwargs)
web_1  |   File "/mfuse/mfuse/api_resources.py", line 47, in get
web_1  |     return jsonify(json.loads(ww.to_json(follow_reference=True)))
web_1  |   File "/usr/local/lib/python3.4/site-packages/mongoengine_goodjson/queryset.py", line 38, in to_json
web_1  |     return json.dumps(lst, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.4/json/__init__.py", line 237, in dumps
web_1  |     **kw).encode(obj)
web_1  |   File "/usr/local/lib/python3.4/site-packages/mongoengine_goodjson/encoder.py", line 40, in __init__
web_1  |     super(GoodJSONEncoder, self).__init__(*args, **kwargs)
web_1  | TypeError: __init__() got an unexpected keyword argument 'follow_reference'
```

**Comment by hiroaki-yamamoto** [comment]
Hi @macfire,

Do you mind if you tell me what `db` and `gj` are?

**Comment by macfire** [comment]
I used factory pattern to init flask_mongoengine (potential problem?)

```python
#extensions.py:
from flask_mongoengine import MongoEngine
db = MongoEngine()

#myapp.py
db.init_app(app)
```

```python
#models.py

from myapp.extensions import db
import mongoengine_goodjson as gj
```

**Comment by hiroaki-yamamoto** [comment]
Ok,

How about using `gj.FollowReferenceField`, not `db.FollowReferenceField`?

**Comment by macfire** [comment]
Sorry for the confusion, I miss-wrote the example above.
My actually code is using `gj.FollowReferenceField`

**Comment by macfire** [comment]
@hiroaki-yamamoto I discovered my error.

I did not append `.get()` method when retrieving objects

```python
#only returns referenced document object ids
user = User.objects(id=ObjectId("57e968198d84c00035c82c63"))
return jsonify(json.loads(user.to_json()))
```

```python
#returns referenced complete document as embedded document
user = User.objects(id=ObjectId("57e968198d84c00035c82c63")).get()
return user
```

**Comment by hiroaki-yamamoto** [comment]
Oh... ok

However, this smells like a bug because I expected FollowReference should work on QuerySet as well as Document.

**Comment by macfire** [comment]
This feature is very helpful. Thanks.

**Comment by macfire** [comment]
You may close this issue, unless you want to leave it open in regards to the bug.

**Comment by hiroaki-yamamoto** [comment]
Please leave as-is, because it needs investigation. If you don't want "many messages", plese unsubscribe.

**Comment by hiroaki-yamamoto** [comment]
# Note

* [queryset.py line 22](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/blob/master/mongoengine_goodjson/queryset.py#L22) doesn't seem to support following reference and `as_pymongo` returns "dicts" in a list. And filtering the fields that is typed as `FollowReferenceField` and ReferenceField.
* For `from_json`, perhaps it seems to be ok because [queryset.py line 56](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/blob/d48b306cb80bd526e1debb66b48796ab08eaa177/mongoengine_goodjson/queryset.py#L56) uses `_from_son`,  but needs tests because it is unclear.

**Comment by hiroaki-yamamoto** [comment]
[Branch: 15_queryset_follow_reference](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/tree/15_queryset_follow_reference)

**Comment by leerobert** [comment]
I really love this library as it makes my model class way less complex. thanks so much for your work... 

I currently get a similar error when attempting to follow reference

```python
>>> d = Drawing.objects(id='57ed40b59d1fa2ab84ea8751').get()
>>> d.to_json()
'{"strokes": [{"drawn_at": "2016-09-29T16:26:27",....
>> d.to_json(follow_reference=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/robert/Projects/GradeForMe/api-v2/env/lib/python3.5/site-packages/mongoengine_goodjson/document.py", line 183, in to_json
    max_depth, current_depth, use_db_field, *args, **kwargs
  File "/Users/robert/Projects/GradeForMe/api-v2/env/lib/python3.5/site-packages/mongoengine_goodjson/document.py", line 66, in _follow_reference
    ) if doc else doc
  File "/Users/robert/Projects/GradeForMe/api-v2/env/lib/python3.5/site-packages/mongoengine/base/document.py", line 422, in to_json
    return json_util.dumps(self.to_mongo(use_db_field), *args, **kwargs)
  File "/Users/robert/Projects/GradeForMe/api-v2/env/lib/python3.5/site-packages/bson/json_util.py", line 113, in dumps
    return json.dumps(_json_convert(obj), *args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Users/robert/Projects/GradeForMe/api-v2/env/lib/python3.5/site-packages/mongoengine_goodjson/encoder.py", line 40, in __init__
    super(GoodJSONEncoder, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'current_depth'
```

This is on the latest branch on pypi (0.11.3).

**Comment by hiroaki-yamamoto** [comment]
@leerobert Could you give me the schema?

**Comment by hiroaki-yamamoto** [comment]
Perhaps, I think your document schema (i.e. class that inherits `Document` or `EmbeddedDocument`) inherits `mongoengine.Document` and `mongoengine.EmbeddedDocument` and they disallow `follow_reference` kwargs.

**Comment by leerobert** [comment]
You're correct I am using mongoengine. I used the FollowReferenceField and had no problems with that. Unfortunately I do have some circular references so I won't be able to use that field for all of my models.

**Comment by hiroaki-yamamoto** [comment]
Okay, anyway I will write test cases.

**Comment by hiroaki-yamamoto** [comment]
```
{
    u"id": text_type(reference.id),
    u"name": u"test",
    u"references": [article_dict.copy()],
    u"ex_info": {
        u"txt": reference_extra_info.txt
    },
    u"ex_ref": {
        u"_id": {u"$oid": str(reference_extra_ref.id)},
        u"ref_txt": reference_extra_ref.ref_txt
    }
}
```

Note: I think this `_id` should be `id` and the id should be str, not dict.

**Comment by hiroaki-yamamoto** [comment]
Done, but there's a missing line on coverage.

**Comment by hiroaki-yamamoto** [comment]
Closed
