### ISSUE TITLE
FollowReferenceField embedding document in parent document in MongoDB

### ISSUE THREAD

**Issue by macfire** [hiroaki-yamamoto/mongoengine-goodjson#17]
I'm using Flask-Admin for CRUD maintenance.
When saving a document with `db.ListField(gj.FollowReferenceField(MyObject)`, the reference field behaves like an EmbeddedDocumentField. That is, the referenced document becomes embedded in the parent document when saved to MongoDB.

 Is this expected behavior?  

I was expecting it continue to save only the reference document's ObjectId in the parent document.

**Comment by hiroaki-yamamoto** [comment]
Perhaps, [mongoengine.base.document:line 303](https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/base/document.py#L303) calls field's `to_mongo` method, so I think it needs something to switch to follow the referenced document not to avoid this problem.

Therefore, I recognized this is a bug.

**Comment by hiroaki-yamamoto** [comment]
Hi @macfire 
I made a change `FollowReferenceField.to_mongo` to acts like `mongoengine.ReferenceField` unless `gj.Document.begin_good_json` is called.

Could you try a0359aade29da833895cf24ae37cb82ba66e4012?

**Comment by macfire** [comment]
@hiroaki-yamamoto 
The change now allows the parent document to save correctly (i.e. only include reference id),
but the JSON output no longer follows reference field.

Do I need to add any kwarg on `to_json` call?

Currently using:
```python
        user = User.objects(username='macfire').get()
       return jsonify(json.loads(user.to_json()))
```

**Comment by hiroaki-yamamoto** [comment]
Oops, sorry I didn't test enough. I will fix it as soon as possible, so please be patient.

**Comment by hiroaki-yamamoto** [comment]
How about [this](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/archive/d3dd3f44d81b829df87ef9ad96b7df0d3a558340.tar.gz)?

**Comment by macfire** [comment]
Partially working as expected.

`to_json()` follows references on first level, but not on nested documents.

```python
class Book(gj.Document):
  name = db.StringField(required=True)
  author = db.StringField(required=True)

class User(gj.Document):
  firstname = db.StringField(required=True)
  books_bought = db.ListField(gj.FollowReferenceField(Book)) # does not follow reference on to_json
  favorite_one = gj.FollowReferenceField(Book)  # follows reference on to_json()
```

**Comment by hiroaki-yamamoto** [comment]
Okay, I added the test: 2fe957eaf17b27d0098042b7f78d8b24555bfeb8, I hope this problem is fixed by [this](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/archive/2fe957eaf17b27d0098042b7f78d8b24555bfeb8.tar.gz)

**Comment by macfire** [comment]
No difference. 

I will test another set of models to verify that I have setup correctly.

**Comment by macfire** [comment]
Ok. I found the difference.
In the test `FollowReferenceFieldListRecursionTest(DBconBase)`, the fields are defined a little differently than what I'm using.

When I create  models based on your test, `to_json()` follows the nested documents;
that is,  when `Ref2` inherits `gj.Document` instead of `gj.EmbeddedDocument`
```python
# From FollowReferenceFieldListRecursionTest(DBconBase)
# using FollowReferenceField for both nested documents

class Ref1(gj.Document):
    name = db.StringField()
 
class Ref2(gj.Document):
    refs = db.ListField(gj.FollowReferenceField(Ref1))
 
class Ref3(gj.Document):
    ref = gj.FollowReferenceField(Ref2)
    refs = db.ListField(gj.FollowReferenceField(Ref2)) 
    oids = db.ListField(db.ObjectIdField(), default=[
        ObjectId for ignore in range(3)
       ])
```

I've been using `EmbeddedDocument` for the middle tier.
```python
# using EmbeddedDocument for first nest, and FollowReferenceField for 2nd

class Book(gj.Document):
  title = db.StringField(required=True)
  author = db.StringField(required=True)

class Bookstore(gj.EmbeddedDocument):
  name = db.StringField()
  books = db.ListField(gj.FollowReferenceField(Book)) # does not follow reference on to_json()

class Buyer(gj.Document):
  firstname = db.StringField(required=True)
  bookstores = db.ListField(db.EmbeddedDocumentField('Bookstore'))
```

**Comment by hiroaki-yamamoto** [comment]
Hmm... it needs to overload `to_mongo`. :nerd_face: 

Anyway, could you try :arrow_up: (i.e. [This](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/archive/400687c30ca612998d5b0cdac740e06340ef1358.tar.gz))?

Currently, the process is a little-bit complex and I think it needs to improve its performance, but probably, it works. (at least I hope so.... maybe)

**Comment by macfire** [comment]
Yes. This last change follows FollowReferenceField in both `EmbeddedDocument` and referenced (nested) `Document`.

Thank you.

**Comment by hiroaki-yamamoto** [comment]
Also, if you have anything about this issue, feel free to comment. If you have other issues create new tickets.
