### ISSUE TITLE
`DynamicField` to_json error

### ISSUE THREAD

**Issue by razodeh** [hiroaki-yamamoto/mongoengine-goodjson#196]
Using `to_json` method on document objects that have a `DynamicField` throws and error
```
AttributeError: 'DynamicField' object has no attribute 'field'
```

**To Reproduce**
1. Create a document Class with `DynamicField` in it
2. Save an object of that class
3. Retrieve that object and use `to_json()`

**Expected behavior**
It supposed to return a json representation of the Document including the dynamic field.

**Comment by hiroaki-yamamoto** [comment]
Seems to be duplicated with #185.

**Comment by SamueleCaprioli97** [comment]
I'm using 1.1.8  and the issue still present. @razodeh Did you solve your behavior?
