### ISSUE TITLE
Exclusion and EmbeddedDocument

### ISSUE THREAD

**Issue by LordNoteworthy** [hiroaki-yamamoto/mongoengine-goodjson#25]
Hello,

I have a question regarding exclusion which is a really nice feature.

I tried to use that in EmbeddedDocuments but it does not seems to work.

For example, you have a parent/child models where in parent you have a list of embedded documents, marking a field inside the child model as exclude_to_json does not exclude the field when doing Model.to_json().

Thanks a lot.

**Comment by hiroaki-yamamoto** [comment]
Seems to be a bug.

**Comment by hiroaki-yamamoto** [comment]
Fixed
