### ISSUE TITLE
No ID replace when returning list of objects

### ISSUE THREAD

**Issue by shlomiLan** [hiroaki-yamamoto/mongoengine-goodjson#34]
When I run this:
```
instance = self.api_class.objects.get_or_404(id=object_id)
return instance.to_json()
```

I get a single document with the ID field formated correctly:
```
{"amount": 1, "descreption": "BBB", "pay_method": "5b51fed52c88845720509757", "id": "5b5101de2c88845fdf1429ed"}
```

But when I do:

```
return self.api_class.objects.to_json()
```

I get the following list without the IDs been formatted:
```
[{"_id": {"$oid": "5b5101de2c88845fdf1429ed"}, "amount": 1, "descreption": "BBB", "pay_method": {"$oid": "5b51fed52c88845720509757"}}, {"_id": {"$oid": "5b5204772c88845720509759"}, "amount": 100, "descreption": "BBB", "pay_method": {"$oid": "5b51fed52c88845720509757"}}]
```

Am I doing anything wrong?

**Comment by hiroaki-yamamoto** [comment]
Well, simple encode/decode is already tested by test code (Check [queryset integration test](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/blob/master/tests/integration/test_queryset.py#L36)), but I think this issue might happens when you code a complex code.

Did you inherit/override something other than `mongoengine_goodjson.document.Document`?

**Comment by shlomiLan** [comment]
I don't understand your solution. 
My class is quite simple but I also used [this package](https://flask-mongoengine.readthedocs.io/en/latest/).
Now I have solved it by implementing the `to_json` method by myself in a class and then all my document Inheriting from it.

**Comment by hiroaki-yamamoto** [comment]
Hi,
As long as I read the code of [that](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/__init__.py), `flask_mongoengine` seems to have their own `Document` class and `QuerySet` class that don't inherit `mongoengine_goodjson.Document` and `mongoengine_goodjson.QuerySet`. As the solution, you will need to create your own classes that inherit the both of `mongoengine_goodjson` classes and `flask_mongoengine` classes.

**Comment by shlomiLan** [comment]
That solved my problem, but I had to set my class as follows:

`class Expense(db.Document, gj.Document)`

the other way (`class Expense(gj.Document, db.Document)`), didn't work
