### ISSUE TITLE
BooleanField to python for "False" executes to True in generate_object_hook

### ISSUE THREAD

**Issue by mohithg** [hiroaki-yamamoto/mongoengine-goodjson#35]
My JSON has `json= {'is_deleted': 'false'}` when I am passing it to `generate_object_hook(document, json)` it returns `is_deleted=True` which is not expected

**Comment by mohithg** [comment]
So this is a bug in mongoengine itself, I will create it there.

**Comment by hiroaki-yamamoto** [comment]
Hi,
I think you are using the object hook in wrong way. Please read [json.load](https://docs.python.org/3.6/library/json.html#json.load) and [json.JSONDecoder](https://docs.python.org/3.6/library/json.html#json.JSONDecoder).

**Comment by mohithg** [comment]
But those won't convert ReferenceFields to DBRef or ObjectId right?

**Comment by mohithg** [comment]
See if https://github.com/hiroaki-yamamoto/mongoengine-goodjson/pull/36 would help

**Comment by hiroaki-yamamoto** [comment]
@mohithg, Converting 'false' string into boolean type is not allowed. #36 is closed.

**Comment by hiroaki-yamamoto** [comment]
But, I'd like to give you a hint about it. Interpreting additional string that can be interpreted into boolean at object hook step is not accepted, however I think creating model field is better (e.g. `SmartBoolField` if we call it?). If you still have a motivation, let's try. 👍
